import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  projectIntroSidebar: [
    {
      type: "autogenerated",
      dirName: "project-intro",
    },
  ],

  meetingSidebar: [
    {
      type: "autogenerated",
      dirName: "meeting",
    },
  ],

  developEnvironmentSidebar: [
    {
      type: "autogenerated",
      dirName: "develop-environment",
    },
  ],

  technicalDecisionSidebar: [
    {
      type: "autogenerated",
      dirName: "technical-decision",
    },
  ],

  mainFeaturesSidebar: [
    {
      type: "autogenerated",
      dirName: "main-features",
    },
  ],
};

export default sidebars;
