import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  changelogSidebar: [
    {
      type: "autogenerated",
      dirName: "changelog",
    },
  ],

  meetingSidebar: [
    {
      type: "autogenerated",
      dirName: "meeting",
    },
  ],

  progressSidebar: [
    {
      type: "autogenerated",
      dirName: "progress",
    },
  ],

  issueSidebar: [
    {
      type: "autogenerated",
      dirName: "issue",
    },
  ],
};

export default sidebars;
