import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  changelogSidebar: [
    {
      type: "autogenerated",
      dirName: "changelog",
    },
  ],

  meetingSidebar: [
    {
      type: "autogenerated",
      dirName: "meeting",
    },
  ],

  pageSidebar: [
    {
      type: "autogenerated",
      dirName: "page",
    },
  ],

  progressSidebar: [
    {
      type: "category",
      label: "프론트엔드",
      collapsed: false,
      items: [
        // ⭐ 템플릿 (templates 폴더에서 가져옴)
        "progress/templates/프론트엔드-작업-기록-템플릿",

        // 📄 프론트엔드 실제 문서들 자동 생성
        {
          type: "autogenerated",
          dirName: "progress/프론트엔드",
        },
      ],
    },

    {
      type: "category",
      label: "공통",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "progress/공통",
        },
      ],
    },

    {
      type: "category",
      label: "백엔드",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "progress/백엔드",
        },
      ],
    },
  ],

  issueSidebar: [
    {
      type: "autogenerated",
      dirName: "issue",
    },
  ],
};

export default sidebars;
